import { t } from 'ttag';

/**
 * All existing ISO 3166-1 alpha-3 country codes
 */
const getIsoAlphaThreeCountryCodes = () => [
  { value: 'ABW', label: t`Aruba` },
  { value: 'AFG', label: t`Afghanistan` },
  { value: 'AGO', label: t`Angola` },
  { value: 'AIA', label: t`Anguilla` },
  { value: 'ALA', label: t`Åland Islands` },
  { value: 'ALB', label: t`Albania` },
  { value: 'AND', label: t`Andorra` },
  { value: 'ARE', label: t`United Arab Emirates` },
  { value: 'ARG', label: t`Argentina` },
  { value: 'ARM', label: t`Armenia` },
  { value: 'ASM', label: t`American Samoa` },
  { value: 'ATA', label: t`Antarctica` },
  { value: 'ATF', label: t`French Southern Territories` },
  { value: 'ATG', label: t`Antigua and Barbuda` },
  { value: 'AUS', label: t`Australia` },
  { value: 'AUT', label: t`Austria` },
  { value: 'AZE', label: t`Azerbaijan` },
  { value: 'BDI', label: t`Burundi` },
  { value: 'BEL', label: t`Belgium` },
  { value: 'BEN', label: t`Benin` },
  { value: 'BES', label: t`Bonaire, Sint Eustatius and Saba` },
  { value: 'BFA', label: t`Burkina Faso` },
  { value: 'BGD', label: t`Bangladesh` },
  { value: 'BGR', label: t`Bulgaria` },
  { value: 'BHR', label: t`Bahrain` },
  { value: 'BHS', label: t`Bahamas` },
  { value: 'BIH', label: t`Bosnia and Herzegovina` },
  { value: 'BLM', label: t`Saint Barthélemy` },
  { value: 'BLR', label: t`Belarus` },
  { value: 'BLZ', label: t`Belize` },
  { value: 'BMU', label: t`Bermuda` },
  { value: 'BOL', label: t`Bolivia, Plurinational State of` },
  { value: 'BRA', label: t`Brazil` },
  { value: 'BRB', label: t`Barbados` },
  { value: 'BRN', label: t`Brunei Darussalam` },
  { value: 'BTN', label: t`Bhutan` },
  { value: 'BVT', label: t`Bouvet Island` },
  { value: 'BWA', label: t`Botswana` },
  { value: 'CAF', label: t`Central African Republic` },
  { value: 'CAN', label: t`Canada` },
  { value: 'CCK', label: t`Cocos (Keeling) Islands` },
  { value: 'CHE', label: t`Switzerland` },
  { value: 'CHL', label: t`Chile` },
  { value: 'CHN', label: t`China` },
  { value: 'CIV', label: t`Côte d'Ivoire` },
  { value: 'CMR', label: t`Cameroon` },
  { value: 'COD', label: t`Congo, the Democratic Republic of the` },
  { value: 'COG', label: t`Congo` },
  { value: 'COK', label: t`Cook Islands` },
  { value: 'COL', label: t`Colombia` },
  { value: 'COM', label: t`Comoros` },
  { value: 'CPV', label: t`Cabo Verde` },
  { value: 'CRI', label: t`Costa Rica` },
  { value: 'CUB', label: t`Cuba` },
  { value: 'CUW', label: t`Curaçao` },
  { value: 'CXR', label: t`Christmas Island` },
  { value: 'CYM', label: t`Cayman Islands` },
  { value: 'CYP', label: t`Cyprus` },
  { value: 'CZE', label: t`Czechia` },
  { value: 'DEU', label: t`Germany` },
  { value: 'DJI', label: t`Djibouti` },
  { value: 'DMA', label: t`Dominica` },
  { value: 'DNK', label: t`Denmark` },
  { value: 'DOM', label: t`Dominican Republic` },
  { value: 'DZA', label: t`Algeria` },
  { value: 'ECU', label: t`Ecuador` },
  { value: 'EGY', label: t`Egypt` },
  { value: 'ERI', label: t`Eritrea` },
  { value: 'ESH', label: t`Western Sahara` },
  { value: 'ESP', label: t`Spain` },
  { value: 'EST', label: t`Estonia` },
  { value: 'ETH', label: t`Ethiopia` },
  { value: 'FIN', label: t`Finland` },
  { value: 'FJI', label: t`Fiji` },
  { value: 'FLK', label: t`Falkland Islands (Malvinas)` },
  { value: 'FRA', label: t`France` },
  { value: 'FRO', label: t`Faroe Islands` },
  { value: 'FSM', label: t`Micronesia, Federated States of` },
  { value: 'GAB', label: t`Gabon` },
  { value: 'GBR', label: t`United Kingdom` },
  { value: 'GEO', label: t`Georgia` },
  { value: 'GGY', label: t`Guernsey` },
  { value: 'GHA', label: t`Ghana` },
  { value: 'GIB', label: t`Gibraltar` },
  { value: 'GIN', label: t`Guinea` },
  { value: 'GLP', label: t`Guadeloupe` },
  { value: 'GMB', label: t`Gambia` },
  { value: 'GNB', label: t`Guinea-Bissau` },
  { value: 'GNQ', label: t`Equatorial Guinea` },
  { value: 'GRC', label: t`Greece` },
  { value: 'GRD', label: t`Grenada` },
  { value: 'GRL', label: t`Greenland` },
  { value: 'GTM', label: t`Guatemala` },
  { value: 'GUF', label: t`French Guiana` },
  { value: 'GUM', label: t`Guam` },
  { value: 'GUY', label: t`Guyana` },
  { value: 'HKG', label: t`Hong Kong` },
  { value: 'HMD', label: t`Heard Island and McDonald Islands` },
  { value: 'HND', label: t`Honduras` },
  { value: 'HRV', label: t`Croatia` },
  { value: 'HTI', label: t`Haiti` },
  { value: 'HUN', label: t`Hungary` },
  { value: 'IDN', label: t`Indonesia` },
  { value: 'IMN', label: t`Isle of Man` },
  { value: 'IND', label: t`India` },
  { value: 'IOT', label: t`British Indian Ocean Territory` },
  { value: 'IRL', label: t`Ireland` },
  { value: 'IRN', label: t`Iran, Islamic Republic of` },
  { value: 'IRQ', label: t`Iraq` },
  { value: 'ISL', label: t`Iceland` },
  { value: 'ISR', label: t`Israel` },
  { value: 'ITA', label: t`Italy` },
  { value: 'JAM', label: t`Jamaica` },
  { value: 'JEY', label: t`Jersey` },
  { value: 'JOR', label: t`Jordan` },
  { value: 'JPN', label: t`Japan` },
  { value: 'KAZ', label: t`Kazakhstan` },
  { value: 'KEN', label: t`Kenya` },
  { value: 'KGZ', label: t`Kyrgyzstan` },
  { value: 'KHM', label: t`Cambodia` },
  { value: 'KIR', label: t`Kiribati` },
  { value: 'KNA', label: t`Saint Kitts and Nevis` },
  { value: 'KOR', label: t`Korea, Republic of` },
  { value: 'KWT', label: t`Kuwait` },
  { value: 'LAO', label: t`Lao People's Democratic Republic` },
  { value: 'LBN', label: t`Lebanon` },
  { value: 'LBR', label: t`Liberia` },
  { value: 'LBY', label: t`Libya` },
  { value: 'LCA', label: t`Saint Lucia` },
  { value: 'LIE', label: t`Liechtenstein` },
  { value: 'LKA', label: t`Sri Lanka` },
  { value: 'LSO', label: t`Lesotho` },
  { value: 'LTU', label: t`Lithuania` },
  { value: 'LUX', label: t`Luxembourg` },
  { value: 'LVA', label: t`Latvia` },
  { value: 'MAC', label: t`Macao` },
  { value: 'MAF', label: t`Saint Martin (French part)` },
  { value: 'MAR', label: t`Morocco` },
  { value: 'MCO', label: t`Monaco` },
  { value: 'MDA', label: t`Moldova, Republic of` },
  { value: 'MDG', label: t`Madagascar` },
  { value: 'MDV', label: t`Maldives` },
  { value: 'MEX', label: t`Mexico` },
  { value: 'MHL', label: t`Marshall Islands` },
  { value: 'MKD', label: t`Macedonia, the former Yugoslav Republic of` },
  { value: 'MLI', label: t`Mali` },
  { value: 'MLT', label: t`Malta` },
  { value: 'MMR', label: t`Myanmar` },
  { value: 'MNE', label: t`Montenegro` },
  { value: 'MNG', label: t`Mongolia` },
  { value: 'MNP', label: t`Northern Mariana Islands` },
  { value: 'MOZ', label: t`Mozambique` },
  { value: 'MRT', label: t`Mauritania` },
  { value: 'MSR', label: t`Montserrat` },
  { value: 'MTQ', label: t`Martinique` },
  { value: 'MUS', label: t`Mauritius` },
  { value: 'MWI', label: t`Malawi` },
  { value: 'MYS', label: t`Malaysia` },
  { value: 'MYT', label: t`Mayotte` },
  { value: 'NAM', label: t`Namibia` },
  { value: 'NCL', label: t`New Caledonia` },
  { value: 'NER', label: t`Niger` },
  { value: 'NFK', label: t`Norfolk Island` },
  { value: 'NGA', label: t`Nigeria` },
  { value: 'NIC', label: t`Nicaragua` },
  { value: 'NIU', label: t`Niue` },
  { value: 'NLD', label: t`Netherlands` },
  { value: 'NOR', label: t`Norway` },
  { value: 'NPL', label: t`Nepal` },
  { value: 'NRU', label: t`Nauru` },
  { value: 'NZL', label: t`New Zealand` },
  { value: 'OMN', label: t`Oman` },
  { value: 'PAK', label: t`Pakistan` },
  { value: 'PAN', label: t`Panama` },
  { value: 'PCN', label: t`Pitcairn` },
  { value: 'PER', label: t`Peru` },
  { value: 'PHL', label: t`Philippines` },
  { value: 'PLW', label: t`Palau` },
  { value: 'PNG', label: t`Papua New Guinea` },
  { value: 'POL', label: t`Poland` },
  { value: 'PRI', label: t`Puerto Rico` },
  { value: 'PRK', label: t`Korea, Democratic People's Republic of` },
  { value: 'PRT', label: t`Portugal` },
  { value: 'PRY', label: t`Paraguay` },
  { value: 'PSE', label: t`Palestine, State of` },
  { value: 'PYF', label: t`French Polynesia` },
  { value: 'QAT', label: t`Qatar` },
  { value: 'REU', label: t`Réunion` },
  { value: 'ROU', label: t`Romania` },
  { value: 'RUS', label: t`Russian Federation` },
  { value: 'RWA', label: t`Rwanda` },
  { value: 'SAU', label: t`Saudi Arabia` },
  { value: 'SDN', label: t`Sudan` },
  { value: 'SEN', label: t`Senegal` },
  { value: 'SGP', label: t`Singapore` },
  { value: 'SGS', label: t`South Georgia and the South Sandwich Islands` },
  { value: 'SHN', label: t`Saint Helena, Ascension and Tristan da Cunha` },
  { value: 'SJM', label: t`Svalbard and Jan Mayen` },
  { value: 'SLB', label: t`Solomon Islands` },
  { value: 'SLE', label: t`Sierra Leone` },
  { value: 'SLV', label: t`El Salvador` },
  { value: 'SMR', label: t`San Marino` },
  { value: 'SOM', label: t`Somalia` },
  { value: 'SPM', label: t`Saint Pierre and Miquelon` },
  { value: 'SRB', label: t`Serbia` },
  { value: 'SSD', label: t`South Sudan` },
  { value: 'STP', label: t`Sao Tome and Principe` },
  { value: 'SUR', label: t`Suriname` },
  { value: 'SVK', label: t`Slovakia` },
  { value: 'SVN', label: t`Slovenia` },
  { value: 'SWE', label: t`Sweden` },
  { value: 'SWZ', label: t`Swaziland` },
  { value: 'SXM', label: t`Sint Maarten (Dutch part)` },
  { value: 'SYC', label: t`Seychelles` },
  { value: 'SYR', label: t`Syrian Arab Republic` },
  { value: 'TCA', label: t`Turks and Caicos Islands` },
  { value: 'TCD', label: t`Chad` },
  { value: 'TGO', label: t`Togo` },
  { value: 'THA', label: t`Thailand` },
  { value: 'TJK', label: t`Tajikistan` },
  { value: 'TKL', label: t`Tokelau` },
  { value: 'TKM', label: t`Turkmenistan` },
  { value: 'TLS', label: t`Timor-Leste` },
  { value: 'TON', label: t`Tonga` },
  { value: 'TTO', label: t`Trinidad and Tobago` },
  { value: 'TUN', label: t`Tunisia` },
  { value: 'TUR', label: t`Turkey` },
  { value: 'TUV', label: t`Tuvalu` },
  { value: 'TWN', label: t`Taiwan, Province of China` },
  { value: 'TZA', label: t`Tanzania, United Republic of` },
  { value: 'UGA', label: t`Uganda` },
  { value: 'UKR', label: t`Ukraine` },
  { value: 'UMI', label: t`United States Minor Outlying Islands` },
  { value: 'URY', label: t`Uruguay` },
  { value: 'USA', label: t`United States of America` },
  { value: 'UZB', label: t`Uzbekistan` },
  { value: 'VAT', label: t`Holy See` },
  { value: 'VCT', label: t`Saint Vincent and the Grenadines` },
  { value: 'VEN', label: t`Venezuela, Bolivarian Republic of` },
  { value: 'VGB', label: t`Virgin Islands, British` },
  { value: 'VIR', label: t`Virgin Islands, U.S.` },
  { value: 'VNM', label: t`VietNam` },
  { value: 'VUT', label: t`Vanuatu` },
  { value: 'WLF', label: t`Wallis and Futuna` },
  { value: 'WSM', label: t`Samoa` },
  { value: 'YEM', label: t`Yemen` },
  { value: 'ZAF', label: t`South Africa` },
  { value: 'ZMB', label: t`Zambia` },
  { value: 'ZWE', label: t`Zimbabwe` },
];

export default getIsoAlphaThreeCountryCodes;
